name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *' # 每天凌晨3点自动运行
  workflow_dispatch: # 允许你手动点击按钮触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: zhaoyuxiangyyds-lab  # 原作者的用户名
          base: main                  # 原作者的分支
          head: main                  # 你自己 fork 仓库的分支
